default: &default
  adapter: mysql2

development:
  <<: *default
  database: 'bookeeper_development'

test:
  <<: *default
  database: bookeeper_test

production:
  <<: *default
  database: bookeeper_production
